pub fn register<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {
    builder.invoke_handler(tauri::generate_handler![
        crate::commands::helper_bridge::get_helper_bridge_status,
        crate::commands::runtime::start_helper_bridge,
        crate::commands::helper_bridge::helper_bridge_worker_status,
        crate::commands::meeting_session::get_meeting_session_status,
        crate::commands::meeting_session::get_meeting_committed_turns,
        crate::commands::meeting_session::start_meeting_translation,
        crate::commands::meeting_session::stop_meeting_translation,
        crate::commands::runtime::verify_models,
        crate::commands::audio::get_input_status,
        crate::commands::audio::list_audio_devices,
        crate::commands::audio::probe_input_device_candidate,
        crate::commands::audio::probe_output_device_candidate,
        crate::commands::settings::load_runtime_settings,
        crate::commands::settings::save_runtime_settings,
        crate::commands::settings::select_audio_device,
        crate::commands::runtime_capture::start_capture,
        crate::commands::runtime_capture::stop_capture,
        crate::commands::text_translate::translate_text,
    ])
}
