figma.showUI(__html__, { width: 580, height: 860 });

const PAGE_NAME = 'TranslateIT Import / Workspace';
const VERSION = 'universal-page-adapter-v5';
let lastRun = null;
let lastDiagnostics = null;
let lastImportMeta = null;
let regular = { family: 'Inter', style: 'Regular' };
let bold = { family: 'Inter', style: 'Bold' };

function send(text, extra) { const msg = { type: 'status', text: text }; extra = extra || {}; Object.keys(extra).forEach(function (key) { msg[key] = extra[key]; }); figma.ui.postMessage(msg); }
async function loadFonts() { try { await figma.loadFontAsync(regular); } catch (_) { regular = { family: 'Roboto', style: 'Regular' }; await figma.loadFontAsync(regular); } try { await figma.loadFontAsync(bold); } catch (_) { bold = regular; } }
function font(isBold) { return isBold ? bold : regular; }
function clean(value) { return String(value || '').replace(/\s+/g, ' ').trim(); }
function safe(value) { return clean(value || 'Layer').slice(0, 96) || 'Layer'; }
function px(value, fallback) { const match = String(value || '').match(/-?\d+(\.\d+)?/); return match ? Number(match[0]) : fallback; }
function rgb(hex) { const value = parseInt(/^#[\da-fA-F]{6}$/.test(hex || '') ? hex.slice(1) : '111827', 16); return { r: ((value >> 16) & 255) / 255, g: ((value >> 8) & 255) / 255, b: (value & 255) / 255 }; }
function paint(hex) { return hex ? [{ type: 'SOLID', color: rgb(hex) }] : []; }
function cssColor(value, fallback) { const raw = String(value || '').trim(); if (!raw || raw === 'transparent' || raw === 'rgba(0, 0, 0, 0)') return fallback || null; const hex = raw.match(/#[\da-fA-F]{6}|#[\da-fA-F]{3}/); if (hex) return hex[0].length === 4 ? '#' + hex[0][1] + hex[0][1] + hex[0][2] + hex[0][2] + hex[0][3] + hex[0][3] : hex[0]; const rgba = raw.match(/rgba?\(([^)]+)\)/); if (rgba) { const parts = rgba[1].split(',').map(function (x) { return parseFloat(x); }); if (parts.length >= 3 && !(parts.length >= 4 && parts[3] === 0)) return '#' + parts.slice(0, 3).map(function (n) { return Math.round(Math.max(0, Math.min(255, n))).toString(16).padStart(2, '0'); }).join(''); } return fallback || null; }
function decodeBase64(value) { const raw = atob(value); const out = new Uint8Array(raw.length); for (let i = 0; i < raw.length; i += 1) out[i] = raw.charCodeAt(i); return out; }
function size(rect, scale) { rect = rect || {}; return { w: Math.max(1, Math.round((rect.w || 1) * scale)), h: Math.max(1, Math.round((rect.h || 1) * scale)) }; }
function pos(rect, parentRect, scale) { rect = rect || {}; parentRect = parentRect || {}; return { x: Math.round(((rect.x || 0) - (parentRect.x || 0)) * scale), y: Math.round(((rect.y || 0) - (parentRect.y || 0)) * scale) }; }
function modeOk(mode) { return mode === 'universal-page-adapter-v1' || mode === 'universal-page-adapter-v1.1' || mode === 'universal-page-adapter-v2' || mode === 'universal-page-adapter-v3' || mode === 'universal-page-adapter-v4' || mode === 'universal-page-adapter-v5'; }

async function workspacePage() { let page = null; for (let i = 0; i < figma.root.children.length; i += 1) if (figma.root.children[i].name === PAGE_NAME) page = figma.root.children[i]; if (!page) page = figma.createPage(); page.name = PAGE_NAME; await figma.setCurrentPageAsync(page); return page; }
function createFrame(name, w, h, fill) { const f = figma.createFrame(); f.name = safe(name); f.resize(w, h); f.layoutMode = 'NONE'; f.paddingTop = 0; f.paddingRight = 0; f.paddingBottom = 0; f.paddingLeft = 0; f.clipsContent = false; f.fills = fill ? paint(fill) : []; f.strokes = []; return f; }
function makeFrame(name, rect, parentRect, scale, fill) { const s = size(rect, scale); const p = pos(rect, parentRect, scale); const f = createFrame(name, s.w, s.h, fill); f.x = p.x; f.y = p.y; return f; }
function screenshotBase(payload, parent, w, h, opacity, name) { if (!payload.screenshot || !payload.screenshot.base64) return null; const r = figma.createRectangle(); r.name = name || 'Locked Website Screenshot Base'; r.resize(w, h); r.x = 0; r.y = 0; const image = figma.createImage(decodeBase64(payload.screenshot.base64)); r.fills = [{ type: 'IMAGE', imageHash: image.hash, scaleMode: 'FILL' }]; r.strokes = []; r.opacity = typeof opacity === 'number' ? opacity : 1; try { r.locked = true; } catch (_) {} parent.appendChild(r); return r; }
function makeBox(layer, parentRect, scale) { const style = layer.style || {}; const rect = figma.createRectangle(); const s = size(layer.rect, scale); const p = pos(layer.rect, parentRect, scale); rect.name = safe((layer.role || 'box') + ' / ' + (layer.name || layer.tag || 'Box')); rect.resize(s.w, s.h); rect.x = p.x; rect.y = p.y; rect.cornerRadius = Math.max(0, px(style.borderRadius, 0) * scale); rect.fills = paint(cssColor(style.backgroundColor, layer.role === 'button-bg' ? '#FFFFFF' : null)); const strokeColor = cssColor(style.borderTopColor || style.borderRightColor || style.borderBottomColor || style.borderLeftColor, null); const strokeWidth = Math.max(px(style.borderTopWidth, 0), px(style.borderRightWidth, 0), px(style.borderBottomWidth, 0), px(style.borderLeftWidth, 0)); rect.strokes = strokeColor && strokeWidth > 0 ? paint(strokeColor) : []; rect.strokeWeight = strokeColor && strokeWidth > 0 ? Math.max(1, strokeWidth * scale) : 0; return rect; }
function makeImage(layer, parentRect, scale) { const fake = { type: layer.type, role: 'image', tag: layer.tag, name: layer.name, rect: layer.rect, style: { backgroundColor: '#E5E7EB', borderRadius: ((layer.style || {}).borderRadius || '0px') } }; const rect = makeBox(fake, parentRect, scale); rect.name = safe('image / ' + (layer.name || 'Image')); if (layer.image && layer.image.base64) { const image = figma.createImage(decodeBase64(layer.image.base64)); rect.fills = [{ type: 'IMAGE', imageHash: image.hash, scaleMode: 'FILL' }]; } return rect; }
function makeText(layer, parentRect, scale, forcedColor) { const style = layer.style || {}; const node = figma.createText(); const value = clean(layer.text || layer.name || ''); const fontSize = Math.max(6, px(style.fontSize, layer.role === 'heading' ? 32 : 14) * scale); const isBold = /bold|600|700|800|900/i.test(String(style.fontWeight || '')) || layer.role === 'heading'; const p = pos(layer.rect, parentRect, scale); node.name = safe((layer.role || 'text') + ' / ' + value.slice(0, 56)); node.fontName = font(isBold); node.characters = value || ' '; node.fontSize = fontSize; node.fills = paint(forcedColor || cssColor(style.color, layer.role === 'heading' ? '#111827' : '#374151')); node.x = p.x; node.y = p.y; try { node.textAutoResize = 'HEIGHT'; const browserWidth = Math.max(20, Math.round(((layer.rect && layer.rect.w) || 80) * scale)); const contentWidth = Math.round(value.length * fontSize * 0.45); node.resize(Math.max(browserWidth, contentWidth, 20), Math.max(fontSize * 1.25, Math.round(((layer.rect && layer.rect.h) || fontSize) * scale))); } catch (_) {} return node; }
function makeLayer(layer, parentRect, scale) { if (!layer || !layer.rect) return null; if (layer.type === 'image') return makeImage(layer, parentRect, scale); if (layer.type === 'text') return makeText(layer, parentRect, scale); if (layer.type === 'box') return makeBox(layer, parentRect, scale); return null; }
function layerSort(a, b) { const rank = { box: 0, image: 1, text: 2 }; return (rank[a.type] || 9) - (rank[b.type] || 9) || (a.rect.y - b.rect.y) || (a.rect.x - b.rect.x); }
function sourceHeight(sections, payload, viewport) { let h = payload.pageHeight || viewport.height || 1600; for (let i = 0; i < sections.length; i += 1) { const r = (sections[i] || {}).rect || {}; h = Math.max(h, (r.y || 0) + (r.h || 0)); } return h; }
function appendLayerList(parent, layers, parentRect, scale, filterFn, forcedTextColor) { (layers || []).slice().filter(function (layer) { return filterFn ? filterFn(layer) : true; }).sort(layerSort).forEach(function (layer) { let node = null; if (layer.type === 'text') node = makeText(layer, parentRect, scale, forcedTextColor); else node = makeLayer(layer, parentRect, scale); if (node) parent.appendChild(node); }); }
function appendComponents(sectionFrame, section, sectionRect, scale) { const components = Array.isArray(section.components) ? section.components : []; if (!components.length) { appendLayerList(sectionFrame, section.layers || [], sectionRect, scale); return; } components.forEach(function (component, index) { const componentRect = component.rect || { x: sectionRect.x, y: sectionRect.y, w: 1, h: 1 }; const componentFrame = makeFrame(component.name || ('Component ' + String(index + 1).padStart(2, '0')), componentRect, sectionRect, scale, null); appendLayerList(componentFrame, component.layers || [], componentRect, scale); sectionFrame.appendChild(componentFrame); }); appendLayerList(sectionFrame, section.looseLayers || [], sectionRect, scale); }

function frameVisualReference(payload, w, h) { const f = createFrame('01 Visual Reference / Pixel Screenshot', w, h, '#FFFFFF'); screenshotBase(payload, f, w, h, 1, 'Locked Visual Reference'); return f; }
function frameProduction(payload, layers, scale, w, h) { const f = createFrame('02 Production Visual Match / Score Target 9+', w, h, '#FFFFFF'); screenshotBase(payload, f, w, h, 1, 'Locked Screenshot Base / Pixel Match'); const map = createFrame('Editable Hit Map / selectable but almost invisible', w, h, null); map.x = 0; map.y = 0; map.fills = []; map.opacity = 0.01; appendLayerList(map, layers, { x: 0, y: 0 }, scale, function (layer) { return layer.type === 'text' || layer.role === 'button-bg' || layer.role === 'button-label' || layer.role === 'link'; }, '#2563EB'); f.appendChild(map); return f; }
function frameEditableTextMap(payload, layers, scale, w, h) { const f = createFrame('03 Editable Text Map / Visible Editing Layer', w, h, '#FFFFFF'); screenshotBase(payload, f, w, h, 0.16, 'Dim Screenshot Reference'); const textMap = createFrame('Editable Text Layers / visible', w, h, null); textMap.x = 0; textMap.y = 0; textMap.fills = []; appendLayerList(textMap, layers, { x: 0, y: 0 }, scale, function (layer) { return layer.type === 'text' || layer.role === 'button-label' || layer.role === 'link'; }, '#111827'); f.appendChild(textMap); return f; }
function frameRawDebug(sections, layers, viewport, scale, h) { const canvas = createFrame('04 Raw Editable Reconstruction / Debug', 1280, h, '#FFFFFF'); if (sections.length) { sections.forEach(function (section, index) { const rect = section.rect || { x: 0, y: 0, w: viewport.width, h: 100 }; const sectionFrame = makeFrame(section.name || ('Section ' + String(index + 1).padStart(2, '0')), rect, { x: 0, y: 0 }, scale, null); sectionFrame.name = safe(section.role === 'header' ? 'Header' : section.role === 'footer' ? 'Footer' : (section.name || 'Section ' + String(index + 1).padStart(2, '0'))); appendComponents(sectionFrame, section, rect, scale); canvas.appendChild(sectionFrame); }); } else { appendLayerList(canvas, layers, { x: 0, y: 0 }, scale); } return canvas; }

async function importUniversal(payload) {
  await loadFonts();
  if (!payload || !modeOk(payload.mode)) throw new Error('Expected Universal Page Adapter payload.');
  const page = await workspacePage();
  const sections = Array.isArray(payload.sections) ? payload.sections : [];
  const layers = Array.isArray(payload.layers) ? payload.layers : [];
  if (!sections.length && !layers.length && !(payload.screenshot && payload.screenshot.base64)) throw new Error('Universal Page Adapter returned no visible layers.');
  const viewport = payload.viewport || { width: 1440, height: 1600 };
  const scale = 1280 / Math.max(1, Number(viewport.width) || 1440);
  const canvasHeight = Math.max(600, Math.round(sourceHeight(sections, payload, viewport) * scale));
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const d = payload.diagnostics || {};
  lastDiagnostics = { layerCount: d.layerCount || layers.length, sectionCount: d.sectionCount || sections.length, componentCount: d.componentCount || 0, imageCount: d.imageCount || 0, textCount: d.textCount || 0, hasScreenshotReference: !!(payload.screenshot && payload.screenshot.base64), outputMode: VERSION, estimatedVisualScore: payload.screenshot ? '9-10' : 'unknown', estimatedPureEditableScore: '4-6' };
  lastImportMeta = { title: payload.title || 'Website Import', url: payload.url || '', adapterMode: payload.mode || '', pluginOutputMode: VERSION, pageHeight: payload.pageHeight || 0, viewport: viewport };

  const run = createFrame(safe((payload.title || 'Website Import') + ' / ' + stamp), 1440, payload.screenshot ? canvasHeight * 4 + 440 : canvasHeight + 220, '#030407');
  run.layoutMode = 'VERTICAL'; run.itemSpacing = 22; run.paddingTop = 40; run.paddingRight = 40; run.paddingBottom = 40; run.paddingLeft = 40; run.primaryAxisSizingMode = 'AUTO'; run.counterAxisSizingMode = 'FIXED';
  const title = figma.createText(); title.name = 'Import Title'; title.fontName = font(true); title.characters = payload.title || 'Website Import'; title.fontSize = 30; title.fills = paint('#F7F9FD'); run.appendChild(title);
  const note = figma.createText(); note.name = 'Import Note'; note.fontName = font(false); note.characters = 'V5 Production Hybrid: pixel visual match, selectable hit-map, visible editable text map, and raw debug. Estimated visual score: ' + lastDiagnostics.estimatedVisualScore + ' / pure editable score: ' + lastDiagnostics.estimatedPureEditableScore + '.'; note.fontSize = 12; note.fills = paint('#8D96A6'); try { note.textAutoResize = 'HEIGHT'; note.resize(1200, 30); } catch (_) {} run.appendChild(note);

  if (payload.screenshot && payload.screenshot.base64) { run.appendChild(frameVisualReference(payload, 1280, canvasHeight)); run.appendChild(frameProduction(payload, layers, scale, 1280, canvasHeight)); run.appendChild(frameEditableTextMap(payload, layers, scale, 1280, canvasHeight)); }
  run.appendChild(frameRawDebug(sections, layers, viewport, scale, canvasHeight));
  page.appendChild(run); figma.viewport.scrollAndZoomIntoView([run]); lastRun = run;
  send('Import complete.\nOutput page: ' + PAGE_NAME + '\nTop-level run: ' + run.name + '\nMode: Universal Page Adapter V5 Production Hybrid\nVisual score target: 9+ using Production Visual Match\nPure editable score: still lower, see Raw Debug\nVisual reference: ' + (lastDiagnostics.hasScreenshotReference ? 'yes' : 'no') + '\nLayers generated: ' + lastDiagnostics.layerCount + '\nSections generated: ' + lastDiagnostics.sectionCount + '\nComponents generated: ' + lastDiagnostics.componentCount + '\nAdapter version: ' + VERSION + '\nReview: 01 reference, 02 production, 03 text map, 04 raw debug.');
}

function exportPackage() { if (!lastRun) return send('No import run found. Import Data first.'); const pkg = { schema: 'translateit.ui-build-package.universal-page.v5', generatedAt: new Date().toISOString(), pluginVersion: VERSION, figmaRun: lastRun.name, source: lastImportMeta || {}, diagnostics: lastDiagnostics || {} }; send('Export complete.', { exportJson: JSON.stringify(pkg, null, 2) }); }
figma.ui.onmessage = async function (msg) { try { msg = msg || {}; if (msg.type === 'import-design-reconstruction' || msg.type === 'import-layout-tree' || msg.type === 'import-source-bundle' || msg.type === 'import-inspector-tree') return await importUniversal(msg.payload || {}); if (msg.type === 'export-ui-package') return exportPackage(); send('Unsupported command: ' + msg.type); } catch (error) { send('Plugin error: ' + (error && error.message ? error.message : error)); } };
