figma.showUI(__html__,{width:580,height:860});
const PAGE='TranslateIT Import / Workspace',VER='Version 0.1 - Alpha',REN='translateit-alpha-v5-strict-source-inspired-renderer';
let reg={family:'Inter',style:'Regular'},bold={family:'Inter',style:'Bold'},last=null;
const A=v=>Array.isArray(v)?v:[],C=v=>String(v||'').replace(/\s+/g,' ').trim(),N=v=>(C(v)||'Layer').slice(0,90),Cut=(v,n)=>{v=C(v);return v.length>n?v.slice(0,n-1)+'…':v};
function rgb(h){let n=parseInt(/^#[0-9a-fA-F]{6}$/.test(h||'')?h.slice(1):'111827',16);return{r:((n>>16)&255)/255,g:((n>>8)&255)/255,b:(n&255)/255}}
function paint(h){return[{type:'SOLID',color:rgb(h||'#111827')}]}function post(t){figma.ui.postMessage({type:'status',text:t})}
function b64(v){let r=atob(v||''),o=new Uint8Array(r.length);for(let i=0;i<r.length;i++)o[i]=r.charCodeAt(i);return o}
async function ready(){try{await figma.loadFontAsync(reg)}catch(e){reg={family:'Roboto',style:'Regular'};await figma.loadFontAsync(reg)}try{await figma.loadFontAsync(bold)}catch(e){bold=reg}let p=figma.root.children.find(x=>x.name===PAGE);if(!p)p=figma.createPage();p.name=PAGE;await figma.setCurrentPageAsync(p)}
function F(n,w,h,c){let x=figma.createFrame();x.name=N(n);x.resize(w,h);x.fills=c?paint(c):[];x.strokes=[];x.clipsContent=false;return x}
function S(n){n.effects=[{type:'DROP_SHADOW',color:{r:0,g:0,b:0,a:.09},offset:{x:0,y:16},radius:36,spread:0,visible:true,blendMode:'NORMAL'}];return n}
function R(p,n,x,y,w,h,c,r,s){let o=figma.createRectangle();o.name=N(n);o.x=x;o.y=y;o.resize(w,h);o.cornerRadius=r||0;o.fills=paint(c||'#fff');o.strokes=s?paint(s):[];o.strokeWeight=s?1:0;p.appendChild(o);return o}
function T(p,n,v,x,y,z,c,b,w){let o=figma.createText();o.name=N(n);o.fontName=b?bold:reg;o.characters=String(v||' ');o.fontSize=z;o.fills=paint(c||'#111827');o.x=x;o.y=y;try{o.textAutoResize='HEIGHT';o.resize(w||240,Math.max(18,z*1.35))}catch(e){}p.appendChild(o);return o}
function I(p,it,x,y,w,h,r){let o=figma.createRectangle();o.name=N('Image / '+C(it&&(it.alt||it.name)||'Media'));o.x=x;o.y=y;o.resize(w,h);o.cornerRadius=r||0;o.strokes=[];if(it&&it.image&&it.image.base64){let im=figma.createImage(b64(it.image.base64));o.fills=[{type:'IMAGE',imageHash:im.hash,scaleMode:'FILL'}]}else{o.fills=paint('#DFE5EA')}p.appendChild(o);return o}
function B(p,v,x,y,w,c,tc){R(p,'Button / '+v,x,y,w,40,c,20);T(p,'Button Label',v,x+18,y+12,10,tc||'#111827',true,w-36)}
function card(parent,name,x,y,w,h){let f=F(name,w,h,'#fff');f.x=x;f.y=y;f.cornerRadius=22;f.strokes=paint('#E6E8EF');f.strokeWeight=1;S(f);parent.appendChild(f);return f}
function byIndex(imgs,idx,fallback){return imgs.find(x=>x.selectorIndex===idx)||imgs[fallback||0]||null}
function build(payload){let m=payload.structuredLayout||{},h=m.header||{},hero=m.hero||{},imgs=A(m.images),cards=A(m.cards),ft=m.footer||{},profile=m.visualProfile||{};let yellow='#F4C84A',green='#087A4B',ink='#111827',mut='#667085',line='#E7EAEF',cream='#FBFAF2',black='#0B1220';let mainImg=byIndex(imgs,hero.primaryImageIndex,0),sideImg=byIndex(imgs,hero.secondaryImageIndex,1);let page=F('01 Source-Inspired Editable Clone / Main Output',1280,1620,cream);page.clipsContent=true;R(page,'Canvas Accent / Soft Yellow',828,108,330,330,'#FFF2B8',165);R(page,'Canvas Accent / Soft Green',52,930,250,250,'#DFF1E8',125);
let head=F('Header / Navigation',1120,76,'#FFFFFF');head.x=80;head.y=42;head.cornerRadius=24;head.strokes=paint(line);head.strokeWeight=1;S(head);page.appendChild(head);R(head,'Logo Mark',24,22,32,32,yellow,9);T(head,'Brand',Cut(h.logoText||payload.title||'Mivubi',30),68,28,14,ink,true,190);A(h.navLinks).slice(0,6).forEach((v,i)=>T(head,'Nav / '+v,v,410+i*74,30,10,ink,false,70));B(head,A(h.ctas)[0]||'Lets Contribute',952,18,142,'#FFFFFF',ink);R(head,'Header Accent Dot',1095,28,18,18,yellow,9);
let heroF=F('Hero / Polished Editorial Composition',1120,690,cream);heroF.x=80;heroF.y=140;page.appendChild(heroF);R(heroF,'Eyebrow Pill',0,38,118,30,yellow,15);T(heroF,'Eyebrow','Mivubi Team',20,47,9,ink,true,90);T(heroF,'Heading',Cut(hero.heading||payload.title||'Unlocking Potential Through Cultural Games.',86),0,92,42,ink,true,360);T(heroF,'Heading Accent','Cultural Games.',0,225,28,yellow,true,330);T(heroF,'Description',Cut(hero.body||'A specialized project team exploring education, art, and culture through interactive digital experiences.',190),0,476,12,mut,false,310);B(heroF,A(hero.ctas)[0]||'Talk with us',0,560,118,yellow,ink);B(heroF,A(hero.ctas)[1]||'Explore',136,560,96,'#FFFFFF',ink);let imgA=S(I(heroF,mainImg,380,36,420,590,24));R(heroF,'Image A Border',380,36,420,590,'#FFFFFF',24,line);let imgB=S(I(heroF,sideImg,835,118,260,430,24));R(heroF,'Image B Border',835,118,260,430,'#FFFFFF',24,line);R(heroF,'Caption A',410,578,158,26,black,13);T(heroF,'Caption A Text',Cut(cards[0]&&cards[0].title||mainImg&&mainImg.alt||'Featured Project',28),426,586,8,'#FFFFFF',false,126);R(heroF,'Caption B',862,516,142,24,black,12);T(heroF,'Caption B Text',Cut(cards[1]&&cards[1].title||sideImg&&sideImg.alt||'Visual Story',26),876,523,8,'#FFFFFF',false,116);[0,1,2].forEach(i=>R(heroF,'Social Icon',i*30,626,22,22,'#FFFFFF',11,line));
let strip=F('Brand Strip / Source Palette Footer Preview',1120,190,'#FFFFFF');strip.x=80;strip.y=850;page.appendChild(strip);R(strip,'Green Brand Block',0,0,398,190,green,0);R(strip,'Yellow Link Block',398,0,722,190,yellow,0);R(strip,'Footer Logo',34,38,32,32,yellow,9);T(strip,'Footer Brand',Cut(h.logoText||'Mivubi',26),78,40,23,'#FFFFFF',true,260);T(strip,'Footer Body',Cut(ft.text||'We are a specialized project team exploring new possibilities using Minecraft for education, art, and culture.',178),36,88,11,'#DFF4EA',false,312);let links=A(ft.links).length?A(ft.links):A(h.navLinks);['Recent Works','Our Program','Contact'].forEach((title,i)=>{let x=462+i*190;T(strip,'Footer Group '+title,title,x,48,13,ink,true,150);links.slice(i*3,i*3+3).forEach((v,j)=>T(strip,'Footer Link '+v,Cut(v,30),x,82+j*24,10,ink,false,150))});[0,1,2].forEach(i=>R(strip,'Footer Social',945+i*30,132,20,20,'#FFFFFF',4,line));
let support=F('Supporting Editable Cards / Component Preview',1120,360,'#FFFFFF');support.x=80;support.y=1090;support.cornerRadius=28;support.strokes=paint(line);support.strokeWeight=1;S(support);page.appendChild(support);T(support,'Support Title','Editable Content System',38,38,26,ink,true,520);T(support,'Support Note','Clean supporting cards are separated from the primary visual clone so the main composition stays readable.',40,78,12,mut,false,760);let items=cards.length?cards.slice(0,3):imgs.slice(0,3).map((im,i)=>({title:im.alt||'Visual Item '+(i+1),body:hero.body||'',imageIndex:im.selectorIndex}));items.forEach((it,i)=>{let x=38+i*352,c=card(support,'Card / '+Cut(it.title||'Item',24),x,132,320,174),im=byIndex(imgs,it.imageIndex,i);I(c,im,16,16,124,98,16);T(c,'Card Title',Cut(it.title||'Content Card',48),156,24,15,ink,true,146);T(c,'Card Body',Cut(it.body||hero.body||'Editable card description.',90),156,62,10,mut,false,142)});T(page,'Visual Profile','visualProfile: '+Cut(profile.template||'source-inspired-editorial',46),80,1518,10,'#98A2B3',false,640);return page}
function shot(payload){let w=1280,ratio=payload.screenshot&&payload.screenshot.width?(payload.screenshot.height||1600)/payload.screenshot.width:1.4,f=F('02 Screenshot Reference / Pure Source',w,Math.max(640,Math.min(9000,Math.round(w*ratio))),'#fff');f.clipsContent=true;if(payload.screenshot&&payload.screenshot.base64){let im=figma.createImage(b64(payload.screenshot.base64)),r=figma.createRectangle();r.name='Locked Screenshot';r.resize(f.width,f.height);r.fills=[{type:'IMAGE',imageHash:im.hash,scaleMode:'FILL'}];r.strokes=[];try{r.locked=true}catch(e){}f.appendChild(r)}return f}
async function imp(payload){await ready();if(!payload||!payload.structuredLayout)throw new Error('Expected structured payload. Start start-alpha-v5.mjs first.');if(!payload.diagnostics||!payload.diagnostics.v5Enhanced)throw new Error('Expected V5 enhanced payload. Run start-alpha-v5.mjs / start-alpha-v5-gated.ps1, not older bridge.');if(!String(payload.adapter||'').includes('v5'))throw new Error('Wrong adapter: expected V5 enhanced structured adapter.');let d=payload.diagnostics||{};let root=F(N((payload.title||'Website')+' / '+new Date().toISOString().replace(/[:.]/g,'-')),1440,2700,'#FFFFFF');T(root,'Run Title',payload.title||'Website Design Clone',80,30,28,'#111827',true,1200);T(root,'Run Note',VER+': strict V5.1 polished source-inspired structured clone. Screenshot is reference only.',80,68,12,'#667085',false,1200);let main=build(payload);main.x=80;main.y=112;root.appendChild(main);let ss=shot(payload);ss.x=80;ss.y=1810;root.appendChild(ss);figma.currentPage.appendChild(root);figma.viewport.scrollAndZoomIntoView([main]);last=root;post('Import complete.\nRenderer: Alpha V5 strict source-inspired structured clone\nPolish: V5.1 visual layout\nMain Output: 01 Source-Inspired Editable Clone / Main Output\nNo raw layer dump.\nScreenshot stays as reference only.\nSections: '+(d.sectionCount||4)+'\nImages: '+(d.imageCount||0)+'\nCaptured Images: '+(d.capturedImageCount||0))}
figma.ui.onmessage=async m=>{try{if(m&&(m.type==='import-design-reconstruction'||m.type==='import-layout-tree'||m.type==='import-source-bundle'||m.type==='import-inspector-tree'))return await imp(m.payload||{});post('Unsupported command: '+(m&&m.type))}catch(e){post('Plugin error: '+(e&&e.message?e.message:e))}};
