figma.showUI(__html__,{width:580,height:860});
const PAGE='TranslateIT Import / Workspace',VER='Version 0.1 - Alpha',REN='translateit-alpha-v5-strict-source-inspired-renderer',BUILD='strict-v5.1-single-engine';
let reg={family:'Inter',style:'Regular'},bold={family:'Inter',style:'Bold'},last=null;
const A=v=>Array.isArray(v)?v:[],C=v=>String(v||'').replace(/\s+/g,' ').trim(),N=v=>(C(v)||'Layer').slice(0,90),Cut=(v,n)=>{v=C(v);return v.length>n?v.slice(0,n-1)+'…':v};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
function cssHex(v,f){let raw=String(v||'').trim();if(/^#[0-9a-fA-F]{6}$/.test(raw))return raw;if(/^#[0-9a-fA-F]{3}$/.test(raw))return '#'+raw[1]+raw[1]+raw[2]+raw[2]+raw[3]+raw[3];let m=raw.match(/rgba?\(([^)]+)\)/);if(!m)return f||'#111827';let p=m[1].split(',').map(x=>parseFloat(x));if(p.length<3||p[3]===0)return f||'#FFFFFF';return '#'+p.slice(0,3).map(n=>Math.round(clamp(n,0,255)).toString(16).padStart(2,'0')).join('')}
function rgb(h){let n=parseInt(/^#[0-9a-fA-F]{6}$/.test(h||'')?h.slice(1):'111827',16);return{r:((n>>16)&255)/255,g:((n>>8)&255)/255,b:(n&255)/255}}
function paint(h){return[{type:'SOLID',color:rgb(h||'#111827')}]}function post(t){figma.ui.postMessage({type:'status',text:t})}
function b64(v){let r=atob(v||''),o=new Uint8Array(r.length);for(let i=0;i<r.length;i++)o[i]=r.charCodeAt(i);return o}
async function ready(){try{await figma.loadFontAsync(reg)}catch(e){reg={family:'Roboto',style:'Regular'};await figma.loadFontAsync(reg)}try{await figma.loadFontAsync(bold)}catch(e){bold=reg}let p=figma.root.children.find(x=>x.name===PAGE);if(!p)p=figma.createPage();p.name=PAGE;await figma.setCurrentPageAsync(p)}
function F(n,w,h,c){let x=figma.createFrame();x.name=N(n);x.resize(w,h);x.fills=c?paint(c):[];x.strokes=[];x.clipsContent=false;return x}
function R(p,n,x,y,w,h,c,r,s){let o=figma.createRectangle();o.name=N(n);o.x=x;o.y=y;o.resize(Math.max(1,w),Math.max(1,h));o.cornerRadius=r||0;o.fills=paint(c||'#fff');o.strokes=s?paint(s):[];o.strokeWeight=s?1:0;p.appendChild(o);return o}
function T(p,n,v,x,y,z,c,b,w,h){let o=figma.createText();o.name=N(n);o.fontName=b?bold:reg;o.characters=String(v||' ');o.fontSize=clamp(z,6,72);o.fills=paint(c||'#111827');o.x=x;o.y=y;try{o.textAutoResize='HEIGHT';o.resize(Math.max(8,w||240),Math.max(12,h||z*1.5))}catch(e){}p.appendChild(o);return o}
function I(p,it,x,y,w,h,r){let o=figma.createRectangle();o.name=N('Image / '+C(it&&(it.alt||it.name)||'Media'));o.x=x;o.y=y;o.resize(Math.max(1,w),Math.max(1,h));o.cornerRadius=r||0;o.strokes=[];if(it&&it.image&&it.image.base64){let im=figma.createImage(b64(it.image.base64));o.fills=[{type:'IMAGE',imageHash:im.hash,scaleMode:'FILL'}]}else{o.fills=paint('#DFE5EA')}p.appendChild(o);return o}
function scaleRect(rect,s,dx,dy){rect=rect||{};return{x:Math.round((rect.x||0)*s+dx),y:Math.round((rect.y||0)*s+dy),w:Math.round((rect.w||120)*s),h:Math.round((rect.h||40)*s)}}
function rad(v,s){let n=parseFloat(String(v||'0').split(' ')[0])||0;return clamp(Math.round(n*s),0,28)}
function byImg(imgs,item){return imgs.find(x=>x.selectorIndex===item.imageIndex)||imgs.find(x=>x.rect&&item.rect&&Math.abs(x.rect.x-item.rect.x)<4&&Math.abs(x.rect.y-item.rect.y)<4)||null}
function shotRef(p,payload,w,h){if(payload.screenshot&&payload.screenshot.base64){let im=figma.createImage(b64(payload.screenshot.base64)),r=figma.createRectangle();r.name='Locked Screenshot';r.resize(w,h);r.fills=[{type:'IMAGE',imageHash:im.hash,scaleMode:'FILL'}];r.strokes=[];try{r.locked=true}catch(e){}p.appendChild(r);return r}return null}
function fallbackBuild(payload,page,s){let m=payload.structuredLayout||{},hero=m.hero||{},imgs=A(m.images),h=m.header||{};let hr=scaleRect(h.rect||{x:0,y:0,w:1440,h:86},s,0,0);R(page,'Fallback Header',hr.x,hr.y,hr.w,Math.max(70,hr.h),'#FFFFFF',0,'#E7EAEF');T(page,'Brand',h.logoText||'Mivubi',hr.x+34,hr.y+28,14,'#111827',true,200);let heroR=scaleRect(hero.rect||{x:80,y:160,w:460,h:120},s,0,0);T(page,'Hero Heading',hero.heading||payload.title||'Website',heroR.x,heroR.y,28,'#111827',true,Math.max(320,heroR.w+120));imgs.slice(0,4).forEach(it=>{let r=scaleRect(it.rect,s,0,0);I(page,it,r.x,r.y,r.w,r.h,12)})}
function build(payload){let m=payload.structuredLayout||{},imgs=A(m.images),els=A(m.measuredElements),srcW=(payload.viewport&&payload.viewport.width)||1440,srcH=payload.pageHeight||payload.screenshot&&payload.screenshot.height||1600,w=1280,s=w/srcW,pageH=clamp(Math.round(srcH*s),900,6200);let page=F('01 Source-Inspired Editable Clone / Main Output',w,pageH,'#FFFFFF');page.clipsContent=true;let useful=els.filter(e=>e&&e.rect&&e.rect.w>2&&e.rect.h>2);let boxes=useful.filter(e=>e.type==='box').sort((a,b)=>b.area-a.area).slice(0,48);let images=useful.filter(e=>e.type==='image').slice(0,24);let buttons=useful.filter(e=>e.type==='button').slice(0,36);let texts=useful.filter(e=>e.type==='text'||e.type==='link').filter(e=>C(e.text).length>0).slice(0,120);
boxes.forEach((e,i)=>{let r=scaleRect(e.rect,s,0,0),bg=cssHex(e.backgroundColor,'#FFFFFF');if(r.w>w*.96&&r.h>pageH*.88)return;R(page,'Measured DOM Box / '+i,r.x,r.y,r.w,r.h,bg,rad(e.borderRadius,s),'#EEF0F3')});
images.forEach((e,i)=>{let r=scaleRect(e.rect,s,0,0),img=byImg(imgs,e);if(!img)return;I(page,img,r.x,r.y,r.w,r.h,rad(e.borderRadius,s)).name=N('Measured DOM Image / '+(img.alt||i+1))});
buttons.forEach((e,i)=>{let r=scaleRect(e.rect,s,0,0),bg=cssHex(e.backgroundColor,'#F4C84A'),col=cssHex(e.color,'#111827');R(page,'Measured DOM Button / '+Cut(e.text||i,24),r.x,r.y,r.w,r.h,bg,rad(e.borderRadius,s),'#E3E6EC');T(page,'Button Text / '+Cut(e.text||i,28),Cut(e.text||'',44),r.x+Math.max(6,10*s),r.y+Math.max(5,8*s),clamp(parseFloat(e.fontSize||'13')*s,7,18),col,Number(e.fontWeight)>=600,Math.max(12,r.w-20),r.h)});
texts.sort((a,b)=>(a.rect.y-b.rect.y)||(a.rect.x-b.rect.x)).forEach((e,i)=>{let r=scaleRect(e.rect,s,0,0),fs=clamp(parseFloat(e.fontSize||'16')*s,7,40),col=cssHex(e.color,'#111827'),boldish=Number(e.fontWeight)>=600||/^h[1-6]$/i.test(e.tag);T(page,(e.type==='link'?'Measured Link / ':'Measured Text / ')+Cut(e.text,28),Cut(e.text,180),r.x,r.y,fs,col,boldish,Math.max(20,r.w+6),Math.max(12,r.h+8))});
if(!useful.length)fallbackBuild(payload,page,s);T(page,'Visual Quality Mode','V5.3 measured DOM reconstruction — editable elements, screenshot only in reference frame',32,pageH-36,10,'#98A2B3',false,760);return page}
function shot(payload){let w=1280,ratio=payload.screenshot&&payload.screenshot.width?(payload.screenshot.height||1600)/payload.screenshot.width:1.4,f=F('02 Screenshot Reference / Pure Source',w,Math.max(640,Math.min(9000,Math.round(w*ratio))),'#fff');f.clipsContent=true;shotRef(f,payload,f.width,f.height);return f}
async function imp(payload){await ready();if(!payload||!payload.structuredLayout)throw new Error('Expected structured payload. Start start-alpha-v5.mjs first.');if(!payload.diagnostics||!payload.diagnostics.v5Enhanced)throw new Error('Expected V5 enhanced payload. Run start-alpha-v5.mjs / start-alpha-v5-gated.ps1, not older bridge.');if(payload.strictV5Engine!==true||!payload.diagnostics.strictV5Engine)throw new Error('Expected strict V5 engine payload. Restart bridge with start-alpha-v5.mjs.');if(payload.engineBuild!==BUILD||payload.diagnostics.engineBuild!==BUILD)throw new Error('Wrong engine build: '+(payload.engineBuild||'missing')+'. Expected '+BUILD+'.');if(!String(payload.adapter||'').includes('v5')||!String(payload.adapter||'').includes('enhanced'))throw new Error('Wrong adapter: expected V5 enhanced structured adapter.');let d=payload.diagnostics||{},main=build(payload),ss=shot(payload),rootH=main.height+ss.height+260;let root=F(N((payload.title||'Website')+' / '+new Date().toISOString().replace(/[:.]/g,'-')),1440,rootH,'#FFFFFF');T(root,'Run Title',payload.title||'Website Design Clone',80,30,28,'#111827',true,1200);T(root,'Run Note',VER+': strict V5.3 measured DOM editable clone. Screenshot is reference only.',80,68,12,'#667085',false,1200);main.x=80;main.y=112;root.appendChild(main);ss.x=80;ss.y=main.y+main.height+80;root.appendChild(ss);figma.currentPage.appendChild(root);figma.viewport.scrollAndZoomIntoView([main]);last=root;post('Import complete.\nRenderer: Alpha V5 strict source-inspired structured clone\nEngine Build: '+BUILD+'\nPolish: V5.3 measured DOM reconstruction\nMain Output: 01 Source-Inspired Editable Clone / Main Output\nNo raw layer dump.\nScreenshot stays as reference only.\nSections: '+(d.sectionCount||4)+'\nImages: '+(d.imageCount||0)+'\nCaptured Images: '+(d.capturedImageCount||0)+'\nMeasured Elements: '+(d.measuredElementCount||0))}
function exp(){figma.ui.postMessage({exportJson:JSON.stringify({version:VER,renderer:REN,engineBuild:BUILD,workspace:PAGE,lastFrame:last?last.name:null,exportedAt:new Date().toISOString(),rules:['01 Source-Inspired Editable Clone / Main Output','02 Screenshot Reference / Pure Source','No raw layer dump'],visualQualityMode:'V5.3 measured DOM reconstruction'},null,2)});post('Export package ready.\nEngine Build: '+BUILD+'\nLast Frame: '+(last?last.name:'none'))}
figma.ui.onmessage=async m=>{try{if(m&&(m.type==='import-design-reconstruction'||m.type==='import-layout-tree'||m.type==='import-source-bundle'||m.type==='import-inspector-tree'))return await imp(m.payload||{});if(m&&m.type==='export-ui-package')return exp();post('Unsupported command: '+(m&&m.type))}catch(e){post('Plugin error: '+(e&&e.message?e.message:e))}};
