import { icon } from "../shared/icons";
import type { RuntimeSettings } from "../shared/types";

export function generalSettingsView(settings: RuntimeSettings, realtimeStatus: string | null, gpuStatus: string | null): string {
  return `<section class="settings-page-title"><h2>General</h2><p>Basic launcher and local runtime preferences.</p></section><article class="audio-card-v22"><div class="audio-grid-v22"><section class="audio-field-group"><h3>Runtime Profile</h3><button class="select-field-v22" type="button"><span>${settings.runtime_profile}</span>${icon("chevron")}</button></section><section class="audio-field-group"><h3>Language Focus</h3><button class="select-field-v22" type="button"><span>${settings.language_focus_mode}</span>${icon("chevron")}</button></section><section class="audio-field-group"><h3>Realtime Status</h3><button class="select-field-v22" type="button"><span>${realtimeStatus ?? "Checking"}</span>${icon("pulse")}</button></section><section class="audio-field-group"><h3>GPU Status</h3><button class="select-field-v22" type="button"><span>${gpuStatus ?? "Checking"}</span>${icon("monitor")}</button></section></div><button id="saveSettingsButton" class="mic-test-button-v22" type="button">Save Settings</button><button id="resetSettingsButton" class="mic-test-button-v22" type="button" style="margin-left:12px;">Save Default</button></article><section class="settings-page-title secondary"><h2>Advanced General Setting</h2><p>Reserved for future launcher preferences.</p></section><article class="advanced-empty-v22"></article>`;
}

export function audioSettingsView(settings: RuntimeSettings): string {
  const voiceEnabled = settings.audio.auto_play_out_voice;
  return `<section class="settings-page-title"><h2>Audio</h2><p>Configure microphone input, voice output, and local capture checks.</p></section><article class="audio-card-v22"><div class="audio-grid-v22"><section class="audio-field-group"><h3>Input Device</h3><button id="checkAudioInputButton" class="select-field-v22" type="button"><span id="audioInputLabel">Default microphone</span>${icon("chevron")}</button></section><section class="audio-field-group"><h3>Input Sensitivity</h3><button id="audioSensitivityButton" class="select-field-v22" type="button"><span>${settings.audio.input_sensitivity}</span>${icon("chevron")}</button></section><section class="audio-field-group"><h3>Voice Output</h3><button id="audioVoiceToggleButton" class="select-field-v22" type="button"><span>${voiceEnabled ? "Enabled" : "Disabled"}</span>${icon("speaker")}</button></section><section class="mic-test-row-v22"><button id="micTestButton" class="mic-test-button-v22" type="button">Test Mic</button><div class="meter-v22"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div></section></div></article><section class="settings-page-title secondary"><h2>Advanced Audio Setting</h2><p>Reserved for future audio device options.</p></section><article class="advanced-empty-v22"></article>`;
}

export function translateSettingsView(settings: RuntimeSettings, sourceLabel: string, targetLabel: string): string {
  const realtimeActive = settings.runtime_profile !== "Quality";
  return `<section class="settings-page-title"><h2>Translate</h2><p>Configure language pair, realtime mode, and output style.</p></section><article class="audio-card-v22"><div class="audio-grid-v22"><section class="audio-field-group"><h3>Source Language</h3><button class="select-field-v22" type="button"><span>${sourceLabel}</span>${icon("translate")}</button></section><section class="audio-field-group"><h3>Target Language</h3><button class="select-field-v22" type="button"><span>${targetLabel}</span>${icon("translate")}</button></section></div><button id="swapLanguageButton" class="mic-test-button-v22" type="button">Swap</button><button id="saveTranslateButton" class="mic-test-button-v22" type="button" style="margin-left:12px;">Save</button></article><section class="settings-page-title secondary"><h2>Realtime</h2><p>Choose faster response or higher quality translation planning.</p></section><article class="voice-card-v22"><div class="voice-grid-v22"><section><h3>Mode</h3><div id="realtimeModeButton" class="radio-row-v22 ${realtimeActive ? "active" : ""}" role="button"><span></span><strong>Fast</strong><em>Prioritize realtime latency.</em></div><div id="qualityModeButton" class="radio-row-v22 ${!realtimeActive ? "active" : ""}" role="button"><span></span><strong>Quality</strong><em>Prioritize careful translation planning.</em></div></section><section><h3>Translate Output</h3><div class="radio-row-v22 active"><span></span><strong>Transcript</strong><em>Always show translated text.</em></div><div class="radio-row-v22 ${settings.audio.auto_play_out_voice ? "active" : ""}"><span></span><strong>Voice</strong><em>Play translated voice when local TTS is available.</em></div></section></div></article><section class="settings-page-title secondary"><h2>Advanced Translate Setting</h2><p>Reserved for future translation preferences.</p></section><article class="advanced-empty-v22"></article>`;
}

export function developerSettingsView(args: {
  progress: number;
  cpu: string;
  ram: string;
  gpu: string;
  gpuStatus: string;
  logRows: string;
  note: string;
  logsExpanded: boolean;
  engineGood: boolean;
}): string {
  return `<section class="settings-page-title"><h2>Developer</h2><p>Simple tools for monitoring runtime health and fixing common issues.</p></section><section class="settings-page-title secondary"><h2>Monitoring</h2><p>Melacak usage hardware dan health engine.</p></section><article class="audio-card-v22"><div class="audio-grid-v22"><section class="audio-field-group"><h3>CPU Usage</h3><button class="select-field-v22" type="button"><span>${args.cpu}</span>${icon("monitor")}</button></section><section class="audio-field-group"><h3>RAM Usage</h3><button class="select-field-v22" type="button"><span>${args.ram}</span>${icon("monitor")}</button></section><section class="audio-field-group"><h3>GPU Usage</h3><button class="select-field-v22" type="button"><span>${args.gpu}</span>${icon("monitor")}</button></section><section class="audio-field-group"><h3>Health Engine</h3><button class="select-field-v22" type="button"><span>${args.engineGood ? "Good" : "Check"}</span>${icon("pulse")}</button></section></div><p style="margin:26px 0 0;color:var(--muted);font-size:13px;">${args.note}</p></article><section class="settings-page-title secondary"><h2>Diagnostic</h2><p>Run checking and review diagnostic logs.</p></section><article class="audio-card-v22"><button id="runDiagnosticButton" class="mic-test-button-v22" type="button">Run Checking</button><span style="margin-left:16px;color:var(--muted);font-weight:800;">${Math.round(args.progress)}%</span><section id="diagnosticLogPanel" class="developer-log-body" style="height:${args.logsExpanded ? 320 : 176}px;margin-top:28px;border:1px solid var(--border-strong);border-radius:18px;background:#080b11;padding:26px;overflow:hidden;">${args.logRows}</section><button id="seeAllLogsButton" class="mic-test-button-v22" type="button" style="margin-top:18px;">${args.logsExpanded ? "Show Less" : "See All Logs"}</button></article><section class="settings-page-title secondary"><h2>Advanced Developer Setting</h2><p>Reserved for future developer options.</p></section><article class="advanced-empty-v22"></article>`;
}
